### ISSUE TITLE
define research question

### ISSUE THREAD

**Issue by marijnbransen1998** [course-dprep/covid19_on_length_of_stay-team1-#1]
These are a few ideas of potential RQs.

- Do superhosts more often offer an entire apartement?
- Has the duration that someone is a host impact on the rating he or she receives?
- Are rooms without wifi considerable less booked?
- Which city has the best value for money? In other words, which city on average has the relative lowest price for the highest rating?
- Are rooms with more facilities always higher rated?
- Welke dag in de week is de meest goedkope optie / het duurst per stad? Kunnen ook nog kijken naar verschillen per land.
- Welke stad in europa had het minst last van de Covid-19 periode?

__Deliverable__:
- One paragraph motivation for this RQ, which can be checked by @hannesdatta.

**Comment by hannesdatta** [comment]
> Which city has the best value for money? In other words, which city on average has the relative lowest price for the highest rating?

This has been studied a lot. Not really my favorite.

**Comment by hannesdatta** [comment]
__Interesting:__
- Welke stad in europa had het minst last van de Covid-19 periode?

__To be checked (in new issues)__:
- [ ] can you get historical data? (these are *current* scrapes, not historical ones)
- [ ] potential to link with other datasets: covid trackers van google, etc., oxford
- [ ] which cities are interesting to take a look at (deliverable: list of city names and corresponding URLs so that you can automatically download them later)

**Comment by hannesdatta** [comment]
- [ ] start building your data pipeline w/ automatically downloading the data files

**Comment by hannesdatta** [comment]
__Summary:__
- closing this issue because we keep on working on #6.

**Comment by KleinJonasUVT** [comment]
It was hard to find historical data for multiple cities. We did find airbnb data for Amsterdam during Covid19. That's why we decided to focus on only Amsterdam. We found an article about the effect of covid 19 on the minimum days of stay in multiple cities in the United States, so we were interested if covid 19 also impacted the minimum days of stay in Amsterdam. Our final research question is therefore:
* What is the impact of Covid19 on the minimum days of stay in Amsterdam?
